# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from refactor.common import csdlpt_pb2 as refactor_dot_common_dot_csdlpt__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in refactor/common/csdlpt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WorkerHeartbeat = channel.unary_unary(
                '/csdlpt.CoordinatorService/WorkerHeartbeat',
                request_serializer=refactor_dot_common_dot_csdlpt__pb2.WorkerHeartbeatMsg.SerializeToString,
                response_deserializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
                _registered_method=True)
        self.IngestorHeartbeat = channel.unary_unary(
                '/csdlpt.CoordinatorService/IngestorHeartbeat',
                request_serializer=refactor_dot_common_dot_csdlpt__pb2.IngestorHeartbeatMsg.SerializeToString,
                response_deserializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
                _registered_method=True)
        self.GetGlobalState = channel.unary_unary(
                '/csdlpt.CoordinatorService/GetGlobalState',
                request_serializer=refactor_dot_common_dot_csdlpt__pb2.StateRequest.SerializeToString,
                response_deserializer=refactor_dot_common_dot_csdlpt__pb2.StateReply.FromString,
                _registered_method=True)
        self.RaftVote = channel.unary_unary(
                '/csdlpt.CoordinatorService/RaftVote',
                request_serializer=refactor_dot_common_dot_csdlpt__pb2.RaftVoteMsg.SerializeToString,
                response_deserializer=refactor_dot_common_dot_csdlpt__pb2.RaftVoteReply.FromString,
                _registered_method=True)
        self.RaftState = channel.unary_unary(
                '/csdlpt.CoordinatorService/RaftState',
                request_serializer=refactor_dot_common_dot_csdlpt__pb2.RaftStateMsg.SerializeToString,
                response_deserializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
                _registered_method=True)
        self.ZkVote = channel.unary_unary(
                '/csdlpt.CoordinatorService/ZkVote',
                request_serializer=refactor_dot_common_dot_csdlpt__pb2.ZkVoteMsg.SerializeToString,
                response_deserializer=refactor_dot_common_dot_csdlpt__pb2.ZkVoteReply.FromString,
                _registered_method=True)
        self.ZkState = channel.unary_unary(
                '/csdlpt.CoordinatorService/ZkState',
                request_serializer=refactor_dot_common_dot_csdlpt__pb2.ZkStateMsg.SerializeToString,
                response_deserializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WorkerHeartbeat(self, request, context):
        """Worker -> Coordinator heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestorHeartbeat(self, request, context):
        """Ingestor -> Coordinator heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalState(self, request, context):
        """Worker -> Coordinator state pull
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RaftVote(self, request, context):
        """Raft HA voting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RaftState(self, request, context):
        """Raft HA state replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZkVote(self, request, context):
        """Simulated ZK HA voting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ZkState(self, request, context):
        """Simulated ZK HA state replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WorkerHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerHeartbeat,
                    request_deserializer=refactor_dot_common_dot_csdlpt__pb2.WorkerHeartbeatMsg.FromString,
                    response_serializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.SerializeToString,
            ),
            'IngestorHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestorHeartbeat,
                    request_deserializer=refactor_dot_common_dot_csdlpt__pb2.IngestorHeartbeatMsg.FromString,
                    response_serializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.SerializeToString,
            ),
            'GetGlobalState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalState,
                    request_deserializer=refactor_dot_common_dot_csdlpt__pb2.StateRequest.FromString,
                    response_serializer=refactor_dot_common_dot_csdlpt__pb2.StateReply.SerializeToString,
            ),
            'RaftVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RaftVote,
                    request_deserializer=refactor_dot_common_dot_csdlpt__pb2.RaftVoteMsg.FromString,
                    response_serializer=refactor_dot_common_dot_csdlpt__pb2.RaftVoteReply.SerializeToString,
            ),
            'RaftState': grpc.unary_unary_rpc_method_handler(
                    servicer.RaftState,
                    request_deserializer=refactor_dot_common_dot_csdlpt__pb2.RaftStateMsg.FromString,
                    response_serializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.SerializeToString,
            ),
            'ZkVote': grpc.unary_unary_rpc_method_handler(
                    servicer.ZkVote,
                    request_deserializer=refactor_dot_common_dot_csdlpt__pb2.ZkVoteMsg.FromString,
                    response_serializer=refactor_dot_common_dot_csdlpt__pb2.ZkVoteReply.SerializeToString,
            ),
            'ZkState': grpc.unary_unary_rpc_method_handler(
                    servicer.ZkState,
                    request_deserializer=refactor_dot_common_dot_csdlpt__pb2.ZkStateMsg.FromString,
                    response_serializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'csdlpt.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('csdlpt.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WorkerHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csdlpt.CoordinatorService/WorkerHeartbeat',
            refactor_dot_common_dot_csdlpt__pb2.WorkerHeartbeatMsg.SerializeToString,
            refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestorHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csdlpt.CoordinatorService/IngestorHeartbeat',
            refactor_dot_common_dot_csdlpt__pb2.IngestorHeartbeatMsg.SerializeToString,
            refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csdlpt.CoordinatorService/GetGlobalState',
            refactor_dot_common_dot_csdlpt__pb2.StateRequest.SerializeToString,
            refactor_dot_common_dot_csdlpt__pb2.StateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RaftVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csdlpt.CoordinatorService/RaftVote',
            refactor_dot_common_dot_csdlpt__pb2.RaftVoteMsg.SerializeToString,
            refactor_dot_common_dot_csdlpt__pb2.RaftVoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RaftState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csdlpt.CoordinatorService/RaftState',
            refactor_dot_common_dot_csdlpt__pb2.RaftStateMsg.SerializeToString,
            refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZkVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csdlpt.CoordinatorService/ZkVote',
            refactor_dot_common_dot_csdlpt__pb2.ZkVoteMsg.SerializeToString,
            refactor_dot_common_dot_csdlpt__pb2.ZkVoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ZkState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csdlpt.CoordinatorService/ZkState',
            refactor_dot_common_dot_csdlpt__pb2.ZkStateMsg.SerializeToString,
            refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AggregatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendWorkerWatermark = channel.unary_unary(
                '/csdlpt.AggregatorService/SendWorkerWatermark',
                request_serializer=refactor_dot_common_dot_csdlpt__pb2.WorkerWatermarkMsg.SerializeToString,
                response_deserializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
                _registered_method=True)


class AggregatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendWorkerWatermark(self, request, context):
        """Heuristic Worker -> Aggregator watermark report
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendWorkerWatermark': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWorkerWatermark,
                    request_deserializer=refactor_dot_common_dot_csdlpt__pb2.WorkerWatermarkMsg.FromString,
                    response_serializer=refactor_dot_common_dot_csdlpt__pb2.EmptyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'csdlpt.AggregatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('csdlpt.AggregatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AggregatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendWorkerWatermark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/csdlpt.AggregatorService/SendWorkerWatermark',
            refactor_dot_common_dot_csdlpt__pb2.WorkerWatermarkMsg.SerializeToString,
            refactor_dot_common_dot_csdlpt__pb2.EmptyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
